---
apiVersion: v1
kind: Namespace
metadata:
  name: externaldns
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: externaldns-vault-cert
  namespace: externaldns
spec:
  dnsNames:
    - "externaldns.acmuic.org"
    - "*.externaldns.svc"
  ipAddresses:
    - 127.0.0.1
  usages:
    - server auth
    - digital signature
    - key encipherment
  secretName: externaldns-vault-cert
  issuerRef:
    kind: ClusterIssuer
    name: acmuic-self-ca
