- hosts: k8s_master
  tasks:
      - block:
          - name: "Checking folders"
            stat:
                path: "{{item}}"
            register: folder_stats
            with_items:
            - ["{{home}}/.bin"]
          - name: "Creating multiple folders without disturbing previous permissions"
            file:
                path: "{{item.item}}"
                state: directory
                mode: 0755
                group: "500"
                owner: "{{ansible_user}}"
            when: item.stat.exists == false
            with_items:
            - "{{folder_stats.results}}"
      - name: Install kubectl
        get_url:
            url: https://storage.googleapis.com/kubernetes-release/release/v{{kubectl_version}}/bin/linux/amd64/kubectl
            dest: "{{home}}/.bin/kubectl"
            mode: '0700'
            owner: "{{ansible_user}}"
            group: "500"
