---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-ingress
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: docker-ingress
    server: 'https://kubernetes.default.svc'
  sources:
    - path: kubernetes/argocd/stacks/docker-ingress
      repoURL: 'git@github.com:acm-uic/IaC.git'
      targetRevision: HEAD
      directory:
        recurse: true
        include: '*.yml'
        exclude: values.yml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
