---
name: 'Terraform PRs for Azure'
on:
  pull_request:
    paths:
      - 'azure/terraform/stacks/**'

jobs:
  terraform:
    name: 'Terraform PR Plan'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_WORKSPACE: prod
      TF_VERSION: 1.3.2
      TF_IN_AUTOMATION: true
      TF_INPUT: 0
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: azure/terraform/stacks/acm-general

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Terraform Format'
        id: fmt
        run: terraform fmt -check

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'Terraform Validate'
        id: validate
        run: terraform validate

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan --var-file "configuration/$TF_WORKSPACE.tfvars"
